version: 2

sources:
  - name: sensor_db
    database: sensor_db
    tables:
      - name: sensordata
        description: 'Larger PEMS data'
      - name: station_summary
        description: 'Summary statistics for each station'
      - name: maindata
        description: 'Sensor data for I80 corridor'
      - name: metadata
        description: 'metadata for each station'
